In [4]:
import pandas as pd

pcos = pd.read_excel("../datasets/PCOS_data_without_infertility.xlsx",
                    sheet_name="Full_new"
                    )

In [5]:
import pandas as pd

# Fix invalid value in beta-HCG column
pcos["II    beta-HCG(mIU/mL)"] = (
    pcos["II    beta-HCG(mIU/mL)"]
    .astype(str)
    .str.rstrip(".")
)

pcos["II    beta-HCG(mIU/mL)"] = pd.to_numeric(
    pcos["II    beta-HCG(mIU/mL)"],
    errors="coerce"
)

# Fix invalid value in AMH column
pcos["AMH(ng/mL)"] = pd.to_numeric(
    pcos["AMH(ng/mL)"],
    errors="coerce"
)

# Fill missing values with median
pcos["II    beta-HCG(mIU/mL)"] = pcos["II    beta-HCG(mIU/mL)"].fillna(
    pcos["II    beta-HCG(mIU/mL)"].median()
)

pcos["AMH(ng/mL)"] = pcos["AMH(ng/mL)"].fillna(
    pcos["AMH(ng/mL)"].median()
)

In [6]:
X = pcos.drop(columns=["PCOS (Y/N)", "Sl. No", "Unnamed: 44"])
y = pcos["PCOS (Y/N)"]

In [7]:
for col in X.columns:
    try:
        pd.to_numeric(X[col])
    except Exception:
        print(col)

In [8]:
pcos.head()

,Sl. No,Patient File No.,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),RR (breaths/min),...,Fast food (Y/N),Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),Follicle No. (L),Follicle No. (R),Avg. F size (L) (mm),Avg. F size (R) (mm),Endometrium (mm),Unnamed: 44
0,1,1,0,28,44.6,152.0,19.300000,15,78,22,...,1.0,0,110,80,3,3,18.0,18.0,8.5,NaN
1,2,2,0,36,65.0,161.5,24.921163,15,74,20,...,0.0,0,120,70,3,5,15.0,14.0,3.7,NaN
2,3,3,1,33,68.8,165.0,25.270891,11,72,18,...,1.0,0,120,80,13,15,18.0,20.0,10.0,NaN
3,4,4,0,37,65.0,148.0,29.674945,13,72,20,...,0.0,0,120,70,2,2,15.0,14.0,7.5,NaN
4,5,5,0,25,52.0,161.0,20.060954,11,72,18,...,0.0,0,120,80,3,4,16.0,14.0,7.0,NaN

In [9]:
pcos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541 entries, 0 to 540
Data columns (total 45 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Sl. No                  541 non-null    int64
 1   Patient File No.        541 non-null    int64
 2   PCOS (Y/N)              541 non-null    int64
 3    Age (yrs)              541 non-null    int64
 4   Weight (Kg)             541 non-null    float64
 5   Height(Cm)              541 non-null    float64
 6   BMI                     541 non-null    float64
 7   Blood Group             541 non-null    int64
 8   Pulse rate(bpm)         541 non-null    int64
 9   RR (breaths/min)        541 non-null    int64
 10  Hb(g/dl)                541 non-null    float64
 11  Cycle(R/I)              541 non-null    int64
 12  Cycle length(days)      541 non-null    int64
 13  Marraige Status (Yrs)   540 non-null    float64
 14  Pregnant(Y/N)           541 non-null    int64
 15  No. of aborptions       541 non-null    int64
 16    I   beta-HCG(mIU/mL)  541 non-null    float64
 17  II    beta-HCG(mIU/mL)  541 non-null    float64
 18  FSH(mIU/mL)             541 non-null    float64
 19  LH(mIU/mL)              541 non-null    float64
 20  FSH/LH                  541 non-null    float64
 21  Hip(inch)               541 non-null    int64
 22  Waist(inch)             541 non-null    int64
 23  Waist:Hip Ratio         541 non-null    float64
 24  TSH (mIU/L)             541 non-null    float64
 25  AMH(ng/mL)              541 non-null    float64
 26  PRL(ng/mL)              541 non-null    float64
 27  Vit D3 (ng/mL)          541 non-null    float64
 28  PRG(ng/mL)              541 non-null    float64
 29  RBS(mg/dl)              541 non-null    float64
 30  Weight gain(Y/N)        541 non-null    int64
 31  hair growth(Y/N)        541 non-null    int64
 32  Skin darkening (Y/N)    541 non-null    int64
 33  Hair loss(Y/N)          541 non-null    int64
 34  Pimples(Y/N)            541 non-null    int64
 35  Fast food (Y/N)         540 non-null    float64
 36  Reg.Exercise(Y/N)       541 non-null    int64
 37  BP _Systolic (mmHg)     541 non-null    int64
 38  BP _Diastolic (mmHg)    541 non-null    int64
 39  Follicle No. (L)        541 non-null    int64
 40  Follicle No. (R)        541 non-null    int64
 41  Avg. F size (L) (mm)    541 non-null    float64
 42  Avg. F size (R) (mm)    541 non-null    float64
 43  Endometrium (mm)        541 non-null    float64
 44  Unnamed: 44             2 non-null      object
dtypes: float64(21), int64(23), object(1)
memory usage: 190.3+ KB

In [10]:
pcos["PCOS (Y/N)"]

0      0
1      0
2      1
3      0
4      0
      ..
536    0
537    0
538    0
539    0
540    1
Name: PCOS (Y/N), Length: 541, dtype: int64

In [11]:
pcos["PCOS (Y/N)"].head()

0    0
1    0
2    1
3    0
4    0
Name: PCOS (Y/N), dtype: int64

In [12]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
)

In [13]:
import sklearn
print(sklearn.__version__)

1.7.2

In [14]:
import pandas as pd

pcos = pd.read_excel("../datasets/PCOS_data_without_infertility.xlsx",
                    sheet_name="Full_new"
                    )

In [15]:
pcos.head()

,Sl. No,Patient File No.,PCOS (Y/N),Age (yrs),Weight (Kg),Height(Cm),BMI,Blood Group,Pulse rate(bpm),RR (breaths/min),...,Fast food (Y/N),Reg.Exercise(Y/N),BP _Systolic (mmHg),BP _Diastolic (mmHg),Follicle No. (L),Follicle No. (R),Avg. F size (L) (mm),Avg. F size (R) (mm),Endometrium (mm),Unnamed: 44
0,1,1,0,28,44.6,152.0,19.300000,15,78,22,...,1.0,0,110,80,3,3,18.0,18.0,8.5,NaN
1,2,2,0,36,65.0,161.5,24.921163,15,74,20,...,0.0,0,120,70,3,5,15.0,14.0,3.7,NaN
2,3,3,1,33,68.8,165.0,25.270891,11,72,18,...,1.0,0,120,80,13,15,18.0,20.0,10.0,NaN
3,4,4,0,37,65.0,148.0,29.674945,13,72,20,...,0.0,0,120,70,2,2,15.0,14.0,7.5,NaN
4,5,5,0,25,52.0,161.0,20.060954,11,72,18,...,0.0,0,120,80,3,4,16.0,14.0,7.0,NaN

In [16]:
pcos.columns.tolist()

['Sl. No',
 'Patient File No.',
 'PCOS (Y/N)',
 ' Age (yrs)',
 'Weight (Kg)',
 'Height(Cm) ',
 'BMI',
 'Blood Group',
 'Pulse rate(bpm) ',
 'RR (breaths/min)',
 'Hb(g/dl)',
 'Cycle(R/I)',
 'Cycle length(days)',
 'Marraige Status (Yrs)',
 'Pregnant(Y/N)',
 'No. of aborptions',
 '  I   beta-HCG(mIU/mL)',
 'II    beta-HCG(mIU/mL)',
 'FSH(mIU/mL)',
 'LH(mIU/mL)',
 'FSH/LH',
 'Hip(inch)',
 'Waist(inch)',
 'Waist:Hip Ratio',
 'TSH (mIU/L)',
 'AMH(ng/mL)',
 'PRL(ng/mL)',
 'Vit D3 (ng/mL)',
 'PRG(ng/mL)',
 'RBS(mg/dl)',
 'Weight gain(Y/N)',
 'hair growth(Y/N)',
 'Skin darkening (Y/N)',
 'Hair loss(Y/N)',
 'Pimples(Y/N)',
 'Fast food (Y/N)',
 'Reg.Exercise(Y/N)',
 'BP _Systolic (mmHg)',
 'BP _Diastolic (mmHg)',
 'Follicle No. (L)',
 'Follicle No. (R)',
 'Avg. F size (L) (mm)',
 'Avg. F size (R) (mm)',
 'Endometrium (mm)',
 'Unnamed: 44']

In [17]:
X = pcos.drop(columns=["PCOS (Y/N)"]) 
y = pcos["PCOS (Y/N)"]
print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

Features Shape: (541, 44)
Target Shape: (541,)

In [18]:
import pandas as pd

In [19]:
pcos = pd.read_excel(
    "../datasets/PCOS_data_without_infertility.xlsx",
    sheet_name="Full_new"
)

In [20]:
X = pcos.drop(columns=["PCOS (Y/N)", "Sl. No", "Unnamed: 44"])
y = pcos["PCOS (Y/N)"]

In [21]:
print(X.columns.tolist)

<bound method IndexOpsMixin.tolist of Index(['Patient File No.', ' Age (yrs)', 'Weight (Kg)', 'Height(Cm) ', 'BMI',
       'Blood Group', 'Pulse rate(bpm) ', 'RR (breaths/min)', 'Hb(g/dl)',
       'Cycle(R/I)', 'Cycle length(days)', 'Marraige Status (Yrs)',
       'Pregnant(Y/N)', 'No. of aborptions', '  I   beta-HCG(mIU/mL)',
       'II    beta-HCG(mIU/mL)', 'FSH(mIU/mL)', 'LH(mIU/mL)', 'FSH/LH',
       'Hip(inch)', 'Waist(inch)', 'Waist:Hip Ratio', 'TSH (mIU/L)',
       'AMH(ng/mL)', 'PRL(ng/mL)', 'Vit D3 (ng/mL)', 'PRG(ng/mL)',
       'RBS(mg/dl)', 'Weight gain(Y/N)', 'hair growth(Y/N)',
       'Skin darkening (Y/N)', 'Hair loss(Y/N)', 'Pimples(Y/N)',
       'Fast food (Y/N)', 'Reg.Exercise(Y/N)', 'BP _Systolic (mmHg)',
       'BP _Diastolic (mmHg)', 'Follicle No. (L)', 'Follicle No. (R)',
       'Avg. F size (L) (mm)', 'Avg. F size (R) (mm)', 'Endometrium (mm)'],
      dtype='object')>

In [22]:
X = X.drop(columns=["Sl. No.", "Patient File No."], errors="ignore")

In [23]:
print(X.isnull().sum())

 Age (yrs)                0
Weight (Kg)               0
Height(Cm)                0
BMI                       0
Blood Group               0
Pulse rate(bpm)           0
RR (breaths/min)          0
Hb(g/dl)                  0
Cycle(R/I)                0
Cycle length(days)        0
Marraige Status (Yrs)     1
Pregnant(Y/N)             0
No. of aborptions         0
  I   beta-HCG(mIU/mL)    0
II    beta-HCG(mIU/mL)    0
FSH(mIU/mL)               0
LH(mIU/mL)                0
FSH/LH                    0
Hip(inch)                 0
Waist(inch)               0
Waist:Hip Ratio           0
TSH (mIU/L)               0
AMH(ng/mL)                0
PRL(ng/mL)                0
Vit D3 (ng/mL)            0
PRG(ng/mL)                0
RBS(mg/dl)                0
Weight gain(Y/N)          0
hair growth(Y/N)          0
Skin darkening (Y/N)      0
Hair loss(Y/N)            0
Pimples(Y/N)              0
Fast food (Y/N)           1
Reg.Exercise(Y/N)         0
BP _Systolic (mmHg)       0
BP _Diastolic (mmHg)      0
Follicle No. (L)          0
Follicle No. (R)          0
Avg. F size (L) (mm)      0
Avg. F size (R) (mm)      0
Endometrium (mm)          0
dtype: int64

In [24]:
X = X.fillna(X.median(numeric_only=True))

In [25]:
print(X.isnull().sum())

 Age (yrs)                0
Weight (Kg)               0
Height(Cm)                0
BMI                       0
Blood Group               0
Pulse rate(bpm)           0
RR (breaths/min)          0
Hb(g/dl)                  0
Cycle(R/I)                0
Cycle length(days)        0
Marraige Status (Yrs)     0
Pregnant(Y/N)             0
No. of aborptions         0
  I   beta-HCG(mIU/mL)    0
II    beta-HCG(mIU/mL)    0
FSH(mIU/mL)               0
LH(mIU/mL)                0
FSH/LH                    0
Hip(inch)                 0
Waist(inch)               0
Waist:Hip Ratio           0
TSH (mIU/L)               0
AMH(ng/mL)                0
PRL(ng/mL)                0
Vit D3 (ng/mL)            0
PRG(ng/mL)                0
RBS(mg/dl)                0
Weight gain(Y/N)          0
hair growth(Y/N)          0
Skin darkening (Y/N)      0
Hair loss(Y/N)            0
Pimples(Y/N)              0
Fast food (Y/N)           0
Reg.Exercise(Y/N)         0
BP _Systolic (mmHg)       0
BP _Diastolic (mmHg)      0
Follicle No. (L)          0
Follicle No. (R)          0
Avg. F size (L) (mm)      0
Avg. F size (R) (mm)      0
Endometrium (mm)          0
dtype: int64

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Data:", X_train.shape)
print("Testing Data:", X_test.shape)

Training Data: (432, 41)
Testing Data: (109, 41)

In [27]:
print(X_train.dtypes)

 Age (yrs)                  int64
Weight (Kg)               float64
Height(Cm)                float64
BMI                       float64
Blood Group                 int64
Pulse rate(bpm)             int64
RR (breaths/min)            int64
Hb(g/dl)                  float64
Cycle(R/I)                  int64
Cycle length(days)          int64
Marraige Status (Yrs)     float64
Pregnant(Y/N)               int64
No. of aborptions           int64
  I   beta-HCG(mIU/mL)    float64
II    beta-HCG(mIU/mL)     object
FSH(mIU/mL)               float64
LH(mIU/mL)                float64
FSH/LH                    float64
Hip(inch)                   int64
Waist(inch)                 int64
Waist:Hip Ratio           float64
TSH (mIU/L)               float64
AMH(ng/mL)                 object
PRL(ng/mL)                float64
Vit D3 (ng/mL)            float64
PRG(ng/mL)                float64
RBS(mg/dl)                float64
Weight gain(Y/N)            int64
hair growth(Y/N)            int64
Skin darkening (Y/N)        int64
Hair loss(Y/N)              int64
Pimples(Y/N)                int64
Fast food (Y/N)           float64
Reg.Exercise(Y/N)           int64
BP _Systolic (mmHg)         int64
BP _Diastolic (mmHg)        int64
Follicle No. (L)            int64
Follicle No. (R)            int64
Avg. F size (L) (mm)      float64
Avg. F size (R) (mm)      float64
Endometrium (mm)          float64
dtype: object

In [28]:
for col in X_train.columns:
    if X_train[col].dtype == 'object':
        print(col)

II    beta-HCG(mIU/mL)
AMH(ng/mL)

In [29]:
for col in X_train.columns:
    if X_train[col].dtype == 'object':
        print(col)
        print(X_train[col].unique()[:20])

II    beta-HCG(mIU/mL)
[1.99 1082.82 638.52 479.6 464.12 173.66 154.48 2.8 155.3 12.37 168.99
 764.83 70.42 1.92 10.45 4490.18 366.04 181.23 15 23.5]
AMH(ng/mL)
[4.1 20 2.28 16.6 3.5 2.9 'a' 5.5 17.6 3.33 7.7 5.6 1.1 1.4 4.63 11.4 3.6
 20.4 4.5 8.75]

In [30]:
for col in X_train.columns:
    if X_train[col].dtype == 'object':
        print(X_train[X_train[col].astype(str).str.contains(r'\.$', regex=True)][col])

123    1.99.
Name: II    beta-HCG(mIU/mL), dtype: object
Series([], Name: AMH(ng/mL), dtype: object)

In [31]:
print(X_train.columns.tolist())

[' Age (yrs)', 'Weight (Kg)', 'Height(Cm) ', 'BMI', 'Blood Group', 'Pulse rate(bpm) ', 'RR (breaths/min)', 'Hb(g/dl)', 'Cycle(R/I)', 'Cycle length(days)', 'Marraige Status (Yrs)', 'Pregnant(Y/N)', 'No. of aborptions', '  I   beta-HCG(mIU/mL)', 'II    beta-HCG(mIU/mL)', 'FSH(mIU/mL)', 'LH(mIU/mL)', 'FSH/LH', 'Hip(inch)', 'Waist(inch)', 'Waist:Hip Ratio', 'TSH (mIU/L)', 'AMH(ng/mL)', 'PRL(ng/mL)', 'Vit D3 (ng/mL)', 'PRG(ng/mL)', 'RBS(mg/dl)', 'Weight gain(Y/N)', 'hair growth(Y/N)', 'Skin darkening (Y/N)', 'Hair loss(Y/N)', 'Pimples(Y/N)', 'Fast food (Y/N)', 'Reg.Exercise(Y/N)', 'BP _Systolic (mmHg)', 'BP _Diastolic (mmHg)', 'Follicle No. (L)', 'Follicle No. (R)', 'Avg. F size (L) (mm)', 'Avg. F size (R) (mm)', 'Endometrium (mm)']

In [32]:
print(X_train.select_dtypes(include='object').columns)

Index(['II    beta-HCG(mIU/mL)', 'AMH(ng/mL)'], dtype='object')

In [33]:
for col in X_train.columns:
    if X_train[col].astype(str).str.contains('1.99.', regex=False).any():
        print("Found in:", col)

Found in: II    beta-HCG(mIU/mL)

In [34]:
for col in X_train.columns:
    try:
        pd.to_numeric(X_train[col])
    except Exception:
        print("Non-numeric column:", col)

Non-numeric column: II    beta-HCG(mIU/mL)
Non-numeric column: AMH(ng/mL)

In [35]:
print(X_train.columns.tolist())

[' Age (yrs)', 'Weight (Kg)', 'Height(Cm) ', 'BMI', 'Blood Group', 'Pulse rate(bpm) ', 'RR (breaths/min)', 'Hb(g/dl)', 'Cycle(R/I)', 'Cycle length(days)', 'Marraige Status (Yrs)', 'Pregnant(Y/N)', 'No. of aborptions', '  I   beta-HCG(mIU/mL)', 'II    beta-HCG(mIU/mL)', 'FSH(mIU/mL)', 'LH(mIU/mL)', 'FSH/LH', 'Hip(inch)', 'Waist(inch)', 'Waist:Hip Ratio', 'TSH (mIU/L)', 'AMH(ng/mL)', 'PRL(ng/mL)', 'Vit D3 (ng/mL)', 'PRG(ng/mL)', 'RBS(mg/dl)', 'Weight gain(Y/N)', 'hair growth(Y/N)', 'Skin darkening (Y/N)', 'Hair loss(Y/N)', 'Pimples(Y/N)', 'Fast food (Y/N)', 'Reg.Exercise(Y/N)', 'BP _Systolic (mmHg)', 'BP _Diastolic (mmHg)', 'Follicle No. (L)', 'Follicle No. (R)', 'Avg. F size (L) (mm)', 'Avg. F size (R) (mm)', 'Endometrium (mm)']

In [36]:
print(X_train.dtypes)

 Age (yrs)                  int64
Weight (Kg)               float64
Height(Cm)                float64
BMI                       float64
Blood Group                 int64
Pulse rate(bpm)             int64
RR (breaths/min)            int64
Hb(g/dl)                  float64
Cycle(R/I)                  int64
Cycle length(days)          int64
Marraige Status (Yrs)     float64
Pregnant(Y/N)               int64
No. of aborptions           int64
  I   beta-HCG(mIU/mL)    float64
II    beta-HCG(mIU/mL)     object
FSH(mIU/mL)               float64
LH(mIU/mL)                float64
FSH/LH                    float64
Hip(inch)                   int64
Waist(inch)                 int64
Waist:Hip Ratio           float64
TSH (mIU/L)               float64
AMH(ng/mL)                 object
PRL(ng/mL)                float64
Vit D3 (ng/mL)            float64
PRG(ng/mL)                float64
RBS(mg/dl)                float64
Weight gain(Y/N)            int64
hair growth(Y/N)            int64
Skin darkening (Y/N)        int64
Hair loss(Y/N)              int64
Pimples(Y/N)                int64
Fast food (Y/N)           float64
Reg.Exercise(Y/N)           int64
BP _Systolic (mmHg)         int64
BP _Diastolic (mmHg)        int64
Follicle No. (L)            int64
Follicle No. (R)            int64
Avg. F size (L) (mm)      float64
Avg. F size (R) (mm)      float64
Endometrium (mm)          float64
dtype: object

In [37]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 432 entries, 244 to 102
Data columns (total 41 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0    Age (yrs)              432 non-null    int64
 1   Weight (Kg)             432 non-null    float64
 2   Height(Cm)              432 non-null    float64
 3   BMI                     432 non-null    float64
 4   Blood Group             432 non-null    int64
 5   Pulse rate(bpm)         432 non-null    int64
 6   RR (breaths/min)        432 non-null    int64
 7   Hb(g/dl)                432 non-null    float64
 8   Cycle(R/I)              432 non-null    int64
 9   Cycle length(days)      432 non-null    int64
 10  Marraige Status (Yrs)   432 non-null    float64
 11  Pregnant(Y/N)           432 non-null    int64
 12  No. of aborptions       432 non-null    int64
 13    I   beta-HCG(mIU/mL)  432 non-null    float64
 14  II    beta-HCG(mIU/mL)  432 non-null    object
 15  FSH(mIU/mL)             432 non-null    float64
 16  LH(mIU/mL)              432 non-null    float64
 17  FSH/LH                  432 non-null    float64
 18  Hip(inch)               432 non-null    int64
 19  Waist(inch)             432 non-null    int64
 20  Waist:Hip Ratio         432 non-null    float64
 21  TSH (mIU/L)             432 non-null    float64
 22  AMH(ng/mL)              432 non-null    object
 23  PRL(ng/mL)              432 non-null    float64
 24  Vit D3 (ng/mL)          432 non-null    float64
 25  PRG(ng/mL)              432 non-null    float64
 26  RBS(mg/dl)              432 non-null    float64
 27  Weight gain(Y/N)        432 non-null    int64
 28  hair growth(Y/N)        432 non-null    int64
 29  Skin darkening (Y/N)    432 non-null    int64
 30  Hair loss(Y/N)          432 non-null    int64
 31  Pimples(Y/N)            432 non-null    int64
 32  Fast food (Y/N)         432 non-null    float64
 33  Reg.Exercise(Y/N)       432 non-null    int64
 34  BP _Systolic (mmHg)     432 non-null    int64
 35  BP _Diastolic (mmHg)    432 non-null    int64
 36  Follicle No. (L)        432 non-null    int64
 37  Follicle No. (R)        432 non-null    int64
 38  Avg. F size (L) (mm)    432 non-null    float64
 39  Avg. F size (R) (mm)    432 non-null    float64
 40  Endometrium (mm)        432 non-null    float64
dtypes: float64(19), int64(20), object(2)
memory usage: 141.8+ KB

In [38]:
for col in X_train.columns:
    mask = X_train[col].astype(str).str.contains('1.99.', regex=False, na=False)
    if mask.any():
        print("Column:", col)
        print(X_train.loc[mask, col])

Column: II    beta-HCG(mIU/mL)
123    1.99.
Name: II    beta-HCG(mIU/mL), dtype: object

In [39]:
print(X_train.columns)

Index([' Age (yrs)', 'Weight (Kg)', 'Height(Cm) ', 'BMI', 'Blood Group',
       'Pulse rate(bpm) ', 'RR (breaths/min)', 'Hb(g/dl)', 'Cycle(R/I)',
       'Cycle length(days)', 'Marraige Status (Yrs)', 'Pregnant(Y/N)',
       'No. of aborptions', '  I   beta-HCG(mIU/mL)', 'II    beta-HCG(mIU/mL)',
       'FSH(mIU/mL)', 'LH(mIU/mL)', 'FSH/LH', 'Hip(inch)', 'Waist(inch)',
       'Waist:Hip Ratio', 'TSH (mIU/L)', 'AMH(ng/mL)', 'PRL(ng/mL)',
       'Vit D3 (ng/mL)', 'PRG(ng/mL)', 'RBS(mg/dl)', 'Weight gain(Y/N)',
       'hair growth(Y/N)', 'Skin darkening (Y/N)', 'Hair loss(Y/N)',
       'Pimples(Y/N)', 'Fast food (Y/N)', 'Reg.Exercise(Y/N)',
       'BP _Systolic (mmHg)', 'BP _Diastolic (mmHg)', 'Follicle No. (L)',
       'Follicle No. (R)', 'Avg. F size (L) (mm)', 'Avg. F size (R) (mm)',
       'Endometrium (mm)'],
      dtype='object')

In [40]:
print(list(X_train.columns))

[' Age (yrs)', 'Weight (Kg)', 'Height(Cm) ', 'BMI', 'Blood Group', 'Pulse rate(bpm) ', 'RR (breaths/min)', 'Hb(g/dl)', 'Cycle(R/I)', 'Cycle length(days)', 'Marraige Status (Yrs)', 'Pregnant(Y/N)', 'No. of aborptions', '  I   beta-HCG(mIU/mL)', 'II    beta-HCG(mIU/mL)', 'FSH(mIU/mL)', 'LH(mIU/mL)', 'FSH/LH', 'Hip(inch)', 'Waist(inch)', 'Waist:Hip Ratio', 'TSH (mIU/L)', 'AMH(ng/mL)', 'PRL(ng/mL)', 'Vit D3 (ng/mL)', 'PRG(ng/mL)', 'RBS(mg/dl)', 'Weight gain(Y/N)', 'hair growth(Y/N)', 'Skin darkening (Y/N)', 'Hair loss(Y/N)', 'Pimples(Y/N)', 'Fast food (Y/N)', 'Reg.Exercise(Y/N)', 'BP _Systolic (mmHg)', 'BP _Diastolic (mmHg)', 'Follicle No. (L)', 'Follicle No. (R)', 'Avg. F size (L) (mm)', 'Avg. F size (R) (mm)', 'Endometrium (mm)']

In [41]:
print(type(X_train))

<class 'pandas.core.frame.DataFrame'>

In [42]:
print(X_train.columns)

Index([' Age (yrs)', 'Weight (Kg)', 'Height(Cm) ', 'BMI', 'Blood Group',
       'Pulse rate(bpm) ', 'RR (breaths/min)', 'Hb(g/dl)', 'Cycle(R/I)',
       'Cycle length(days)', 'Marraige Status (Yrs)', 'Pregnant(Y/N)',
       'No. of aborptions', '  I   beta-HCG(mIU/mL)', 'II    beta-HCG(mIU/mL)',
       'FSH(mIU/mL)', 'LH(mIU/mL)', 'FSH/LH', 'Hip(inch)', 'Waist(inch)',
       'Waist:Hip Ratio', 'TSH (mIU/L)', 'AMH(ng/mL)', 'PRL(ng/mL)',
       'Vit D3 (ng/mL)', 'PRG(ng/mL)', 'RBS(mg/dl)', 'Weight gain(Y/N)',
       'hair growth(Y/N)', 'Skin darkening (Y/N)', 'Hair loss(Y/N)',
       'Pimples(Y/N)', 'Fast food (Y/N)', 'Reg.Exercise(Y/N)',
       'BP _Systolic (mmHg)', 'BP _Diastolic (mmHg)', 'Follicle No. (L)',
       'Follicle No. (R)', 'Avg. F size (L) (mm)', 'Avg. F size (R) (mm)',
       'Endometrium (mm)'],
      dtype='object')

In [43]:
Index(['Age', 'Gender', 'Salary', 'Purchased'], dtype='object')

NameError: name 'Index' is not defined

In [ ]:
X_train

In [ ]:
print(X_train.columns)

In [ ]:
X_train.columns

In [ ]:
type(X_train)

In [ ]:
X_train = X_train.drop(columns=["S1. No", "Unnamed: 44"], errors="ignore")
X_test = X_test.drop(columns=["S1. No", "Unnamed: 44"], errors="ignore")

In [ ]:
X_train.columns

In [ ]:
X_train.isnull().sum()

In [44]:
X_train = X_train.fillna(X_train.mean(numeric_only=True))
X_test = X_test.fillna(X_train.mean(numeric_only=True))

In [45]:
from sklearn.linear_model import LogisticRegression

In [46]:
model = LogisticRegression(max_iter=1000)

In [47]:
model.fit(X_train, y_train)

ValueError: could not convert string to float: '1.99.'

In [68]:
print("Model trained successfully!")
print("Number of features:", len(model.feature_names_in_))
print(model.feature_names_in_)

Model trained successfully!
Number of features: 42
['Patient File No.' ' Age (yrs)' 'Weight (Kg)' 'Height(Cm) ' 'BMI'
 'Blood Group' 'Pulse rate(bpm) ' 'RR (breaths/min)' 'Hb(g/dl)'
 'Cycle(R/I)' 'Cycle length(days)' 'Marraige Status (Yrs)' 'Pregnant(Y/N)'
 'No. of aborptions' '  I   beta-HCG(mIU/mL)' 'II    beta-HCG(mIU/mL)'
 'FSH(mIU/mL)' 'LH(mIU/mL)' 'FSH/LH' 'Hip(inch)' 'Waist(inch)'
 'Waist:Hip Ratio' 'TSH (mIU/L)' 'AMH(ng/mL)' 'PRL(ng/mL)'
 'Vit D3 (ng/mL)' 'PRG(ng/mL)' 'RBS(mg/dl)' 'Weight gain(Y/N)'
 'hair growth(Y/N)' 'Skin darkening (Y/N)' 'Hair loss(Y/N)' 'Pimples(Y/N)'
 'Fast food (Y/N)' 'Reg.Exercise(Y/N)' 'BP _Systolic (mmHg)'
 'BP _Diastolic (mmHg)' 'Follicle No. (L)' 'Follicle No. (R)'
 'Avg. F size (L) (mm)' 'Avg. F size (R) (mm)' 'Endometrium (mm)']

In [ ]:
pcos["II    beta-HCG(mIU/mL)"] = (
    pcos["II    beta-HCG(mIU/mL)"]
    .astype(str)
    .str.rstrip(".")
)

pcos["II    beta-HCG(mIU/mL)"] = pd.to_numeric(
    pcos["II    beta-HCG(mIU/mL)"],
    errors="coerce"
)

In [48]:
print(pcos["II    beta-HCG(mIU/mL)"].isna().sum())

0

In [49]:
X_train["II    beta-HCG(mIU/mL)"] = pd.to_numeric(
    X_train["II    beta-HCG(mIU/mL)"].astype(str).str.replace(".", "", regex=False).str[:-2] + "." + X_train["II    beta-HCG(mIU/mL)"].astype(str).str[-2:],
    errors="coerce"
)

X_test["II    beta-HCG(mIU/mL)"] = pd.to_numeric(
    X_test["II    beta-HCG(mIU/mL)"].astype(str).str.replace(".", "", regex=False).str[:-2] + "." + X_test["II    beta-HCG(mIU/mL)"].astype(str).str[-2:],
    errors="coerce"
)

In [50]:
model.fit(X_train, y_train)

ValueError: could not convert string to float: 'a'

In [51]:
for col in X_train.columns:
    if X_train[col].dtype == "object":
        print("\nColumn:", col)
        print(X_train[col].unique()[:20])

Column: AMH(ng/mL)
[4.1 20 2.28 16.6 3.5 2.9 'a' 5.5 17.6 3.33 7.7 5.6 1.1 1.4 4.63 11.4 3.6
 20.4 4.5 8.75]

In [52]:
for col in X_train.columns:
    X_train[col] = pd.to_numeric(X_train[col], errors="coerce")

X_train = X_train.fillna(X_train.median(numeric_only=True))

In [53]:
model.fit(X_train, y_train)

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [54]:
y_pred = model.predict(X_test)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
X_train.isnull().sum().sum(), X_test.isnull().sum().sum()

In [ ]:
print(X_test.isnull().sum().sum())

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
print(X_test.dtypes[X_test.dtypes == "object"])

In [ ]:
for col in X_test.columns:
    if X_test[col].isnull().sum() > 0:
        print(col, X_test[col].isnull().sum())

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

In [55]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

NameError: name 'y_pred' is not defined

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

In [ ]:
from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

y_prob = model.predict_proba(X_test)[:, 1]

fpr, tpr, thresholds = roc_curve(y_test, y_prob)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.2f}")
plt.plot([0,1], [0,1], linestyle="--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

In [56]:
from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

y_prob = model.predict_proba(X_test)[:, 1]

fpr, tpr, thresholds = roc_curve(y_test, y_prob)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.2f}")
plt.plot([0,1], [0,1], linestyle="--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

y_prob = model.predict_proba(X_test)[:, 1]

fpr, tpr, thresholds = roc_curve(y_test, y_prob)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.2f}")
plt.plot([0,1], [0,1], linestyle="--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

In [ ]:
import joblib

joblib.dump(model, "../models/pcos_logistic_model.pkl")

print("Model saved successfully!")

In [ ]:
joblib.dump(model, "pcos_logistic_model.pkl")

print("Model saved successfully!")

In [ ]:
import pandas as pd

importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Coefficient": model.coef_[0]
})

importance = importance.sort_values(by="Coefficient", ascending=False)

print(importance.head(10))

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

In [ ]:
model.fit(X_train, y_train)

In [ ]:
print(model.feature_names_in_)
print(len(model.feature_names_in_))

In [ ]:
import pandas as pd

importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Coefficient": model.coef_[0]
})

importance = importance.sort_values(by="Coefficient", ascending=False)

print(importance.head(10))

# Conclusion

In this project, a Machine Learning model was developed to predict the risk of Polycystic Ovary Syndrome (PCOS) using women's health data. The dataset was successfully loaded, explored, and preprocessed by handling missing values and removing unnecessary features. The data was then divided into training and testing sets.

A Logistic Regression model was trained and evaluated using standard performance metrics such as Accuracy, Confusion Matrix, Classification Report, and ROC Curve. The trained model was saved for future use in a web application.

This project demonstrates how Machine Learning can assist in the early detection of PCOS, helping to identify potential health risks using patient data. The developed model serves as the foundation for the **Silent Health Risk Detector for Women**, which can later be extended to predict other diseases such as Anemia, Diabetes, Thyroid disorders, and Heart Stroke Risk.

# Future Scope

- Integrate prediction models for Anemia, Diabetes, Thyroid Disease, and Heart Stroke Risk.
- Develop a user-friendly web application using Flask.
- Store user health records in a database.
- Improve prediction accuracy using advanced Machine Learning algorithms such as Random Forest, XGBoost, and Gradient Boosting.
- Deploy the application online for real-time access.

In [ ]:
print(X.shape)
print(X.columns.tolist())

In [ ]:
for col in X.columns:
    try:
        pd.to_numeric(X[col])
    except Exception:
        print(f"Problem in column: {col}")
        print(X.loc[pd.to_numeric(X[col], errors="coerce").isna(), col].unique())
        print("-" * 50)

In [ ]:
X = pcos.drop(columns=["PCOS (Y/N)", "Sl. No", "Unnamed: 44"])
y = pcos["PCOS (Y/N)"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

In [ ]:
model.fit(X_train, y_train)

In [ ]:
print(X.isnull().sum()[X.isnull().sum() > 0])

In [57]:
# Fill missing values with the median of each column
pcos["Marraige Status (Yrs)"] = pcos["Marraige Status (Yrs)"].fillna(
    pcos["Marraige Status (Yrs)"].median()
)

pcos["Fast food (Y/N)"] = pcos["Fast food (Y/N)"].fillna(
    pcos["Fast food (Y/N)"].median()
)

In [67]:
X = pcos.drop(
    columns=[
        "PCOS (Y/N)",
        "Sl. No",
        "Unnamed: 44",
        "Patient File No."
    ]
)

y = pcos["PCOS (Y/N)"]

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)
print(X.columns.tolist())

Features Shape: (541, 41)
Target Shape: (541,)
[' Age (yrs)', 'Weight (Kg)', 'Height(Cm) ', 'BMI', 'Blood Group', 'Pulse rate(bpm) ', 'RR (breaths/min)', 'Hb(g/dl)', 'Cycle(R/I)', 'Cycle length(days)', 'Marraige Status (Yrs)', 'Pregnant(Y/N)', 'No. of aborptions', '  I   beta-HCG(mIU/mL)', 'II    beta-HCG(mIU/mL)', 'FSH(mIU/mL)', 'LH(mIU/mL)', 'FSH/LH', 'Hip(inch)', 'Waist(inch)', 'Waist:Hip Ratio', 'TSH (mIU/L)', 'AMH(ng/mL)', 'PRL(ng/mL)', 'Vit D3 (ng/mL)', 'PRG(ng/mL)', 'RBS(mg/dl)', 'Weight gain(Y/N)', 'hair growth(Y/N)', 'Skin darkening (Y/N)', 'Hair loss(Y/N)', 'Pimples(Y/N)', 'Fast food (Y/N)', 'Reg.Exercise(Y/N)', 'BP _Systolic (mmHg)', 'BP _Diastolic (mmHg)', 'Follicle No. (L)', 'Follicle No. (R)', 'Avg. F size (L) (mm)', 'Avg. F size (R) (mm)', 'Endometrium (mm)']

In [59]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [60]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

In [61]:
model.fit(X_train, y_train)

ValueError: could not convert string to float: '1.99.'

In [66]:
print(model.feature_names_in_)
print(len(model.feature_names_in_))

['Patient File No.' ' Age (yrs)' 'Weight (Kg)' 'Height(Cm) ' 'BMI'
 'Blood Group' 'Pulse rate(bpm) ' 'RR (breaths/min)' 'Hb(g/dl)'
 'Cycle(R/I)' 'Cycle length(days)' 'Marraige Status (Yrs)' 'Pregnant(Y/N)'
 'No. of aborptions' '  I   beta-HCG(mIU/mL)' 'II    beta-HCG(mIU/mL)'
 'FSH(mIU/mL)' 'LH(mIU/mL)' 'FSH/LH' 'Hip(inch)' 'Waist(inch)'
 'Waist:Hip Ratio' 'TSH (mIU/L)' 'AMH(ng/mL)' 'PRL(ng/mL)'
 'Vit D3 (ng/mL)' 'PRG(ng/mL)' 'RBS(mg/dl)' 'Weight gain(Y/N)'
 'hair growth(Y/N)' 'Skin darkening (Y/N)' 'Hair loss(Y/N)' 'Pimples(Y/N)'
 'Fast food (Y/N)' 'Reg.Exercise(Y/N)' 'BP _Systolic (mmHg)'
 'BP _Diastolic (mmHg)' 'Follicle No. (L)' 'Follicle No. (R)'
 'Avg. F size (L) (mm)' 'Avg. F size (R) (mm)' 'Endometrium (mm)']
42

In [ ]:
import joblib

joblib.dump(model, "../models/pcos_model.pkl")

print("PCOS Model Saved Successfully!")

In [62]:
print(X.columns.tolist())

['Patient File No.', ' Age (yrs)', 'Weight (Kg)', 'Height(Cm) ', 'BMI', 'Blood Group', 'Pulse rate(bpm) ', 'RR (breaths/min)', 'Hb(g/dl)', 'Cycle(R/I)', 'Cycle length(days)', 'Marraige Status (Yrs)', 'Pregnant(Y/N)', 'No. of aborptions', '  I   beta-HCG(mIU/mL)', 'II    beta-HCG(mIU/mL)', 'FSH(mIU/mL)', 'LH(mIU/mL)', 'FSH/LH', 'Hip(inch)', 'Waist(inch)', 'Waist:Hip Ratio', 'TSH (mIU/L)', 'AMH(ng/mL)', 'PRL(ng/mL)', 'Vit D3 (ng/mL)', 'PRG(ng/mL)', 'RBS(mg/dl)', 'Weight gain(Y/N)', 'hair growth(Y/N)', 'Skin darkening (Y/N)', 'Hair loss(Y/N)', 'Pimples(Y/N)', 'Fast food (Y/N)', 'Reg.Exercise(Y/N)', 'BP _Systolic (mmHg)', 'BP _Diastolic (mmHg)', 'Follicle No. (L)', 'Follicle No. (R)', 'Avg. F size (L) (mm)', 'Avg. F size (R) (mm)', 'Endometrium (mm)']

In [63]:
X = pcos.drop(columns=[
    "PCOS (Y/N)",
    "Sl. No",
    "Patient File No.",
    "Unnamed: 44"
])

y = pcos["PCOS (Y/N)"]

In [64]:
import joblib

joblib.dump(model, "../models/pcos_model.pkl")

print("PCOS Model Saved Successfully!")

PCOS Model Saved Successfully!

In [69]:
print(X.shape)

(541, 41)

In [70]:
X = pcos.drop(
    columns=[
        "PCOS (Y/N)",
        "Sl. No",
        "Unnamed: 44",
        "Patient File No."
    ]
)

y = pcos["PCOS (Y/N)"]

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

Features Shape: (541, 41)
Target Shape: (541,)

In [71]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training shape:", X_train.shape)
print("Testing shape:", X_test.shape)

Training shape: (432, 41)
Testing shape: (109, 41)

In [72]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

print("New PCOS model created!")

New PCOS model created!

In [73]:
model.fit(X_train, y_train)

print("PCOS model trained successfully!")

ValueError: could not convert string to float: '1.99.'

In [74]:
import pandas as pd

# Fix invalid numeric values
pcos["II    beta-HCG(mIU/mL)"] = pd.to_numeric(
    pcos["II    beta-HCG(mIU/mL)"],
    errors="coerce"
)

pcos["AMH(ng/mL)"] = pd.to_numeric(
    pcos["AMH(ng/mL)"],
    errors="coerce"
)

# Check missing values created by invalid entries
print("Missing values:")
print(pcos[["II    beta-HCG(mIU/mL)", "AMH(ng/mL)"]].isnull().sum())

Missing values:
II    beta-HCG(mIU/mL)    1
AMH(ng/mL)                1
dtype: int64

In [75]:
pcos["II    beta-HCG(mIU/mL)"] = pcos["II    beta-HCG(mIU/mL)"].fillna(
    pcos["II    beta-HCG(mIU/mL)"].median()
)

pcos["AMH(ng/mL)"] = pcos["AMH(ng/mL)"].fillna(
    pcos["AMH(ng/mL)"].median()
)

print("Missing values fixed!")

print(
    pcos[["II    beta-HCG(mIU/mL)", "AMH(ng/mL)"]]
    .isnull()
    .sum()
)

Missing values fixed!
II    beta-HCG(mIU/mL)    0
AMH(ng/mL)                0
dtype: int64

In [76]:
X = pcos.drop(
    columns=[
        "PCOS (Y/N)",
        "Sl. No",
        "Unnamed: 44",
        "Patient File No."
    ]
)

y = pcos["PCOS (Y/N)"]

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

Features Shape: (541, 41)
Target Shape: (541,)

In [79]:
print(X.dtypes[X.dtypes == "object"])

Series([], dtype: object)

In [80]:
# Check missing values
print("Missing values:")
print(X.isnull().sum()[X.isnull().sum() > 0])

# Check infinite values
import numpy as np
print("\nInfinite values:")
print(np.isinf(X.select_dtypes(include=np.number)).sum()[np.isinf(X.select_dtypes(include=np.number)).sum() > 0])

# Check data types
print("\nData types:")
print(X.dtypes)

Missing values:
Series([], dtype: int64)

Infinite values:
Series([], dtype: int64)

Data types:
 Age (yrs)                  int64
Weight (Kg)               float64
Height(Cm)                float64
BMI                       float64
Blood Group                 int64
Pulse rate(bpm)             int64
RR (breaths/min)            int64
Hb(g/dl)                  float64
Cycle(R/I)                  int64
Cycle length(days)          int64
Marraige Status (Yrs)     float64
Pregnant(Y/N)               int64
No. of aborptions           int64
  I   beta-HCG(mIU/mL)    float64
II    beta-HCG(mIU/mL)    float64
FSH(mIU/mL)               float64
LH(mIU/mL)                float64
FSH/LH                    float64
Hip(inch)                   int64
Waist(inch)                 int64
Waist:Hip Ratio           float64
TSH (mIU/L)               float64
AMH(ng/mL)                float64
PRL(ng/mL)                float64
Vit D3 (ng/mL)            float64
PRG(ng/mL)                float64
RBS(mg/dl)                float64
Weight gain(Y/N)            int64
hair growth(Y/N)            int64
Skin darkening (Y/N)        int64
Hair loss(Y/N)              int64
Pimples(Y/N)                int64
Fast food (Y/N)           float64
Reg.Exercise(Y/N)           int64
BP _Systolic (mmHg)         int64
BP _Diastolic (mmHg)        int64
Follicle No. (L)            int64
Follicle No. (R)            int64
Avg. F size (L) (mm)      float64
Avg. F size (R) (mm)      float64
Endometrium (mm)          float64
dtype: object

In [81]:
print("\nNaN count:", X.isna().sum().sum())
print("Infinity count:", np.isinf(X.select_dtypes(include=np.number)).sum().sum())

NaN count: 0
Infinity count: 0

In [82]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training shape:", X_train.shape)
print("Testing shape:", X_test.shape)

# Create model
model = LogisticRegression(max_iter=2000)

# Train
model.fit(X_train, y_train)

print("PCOS model trained successfully!")

Training shape: (432, 41)
Testing shape: (109, 41)
PCOS model trained successfully!

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 2000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=2000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [83]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

# Make predictions
y_pred = model.predict(X_test)

# Evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("PCOS MODEL PERFORMANCE")
print("----------------------")
print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

PCOS MODEL PERFORMANCE
----------------------
Accuracy : 0.8990825688073395
Precision: 0.8378378378378378
Recall   : 0.8611111111111112
F1 Score : 0.8493150684931506

Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.92      0.92        73
           1       0.84      0.86      0.85        36

    accuracy                           0.90       109
   macro avg       0.88      0.89      0.89       109
weighted avg       0.90      0.90      0.90       109


Confusion Matrix:
[[67  6]
 [ 5 31]]

In [84]:
import joblib

joblib.dump(model, "pcos_logistic_model.pkl")

print("PCOS model saved successfully!")

PCOS model saved successfully!

In [85]:
import os

print(os.path.exists("pcos_logistic_model.pkl"))

True

In [86]:
import joblib

test_model = joblib.load("pcos_logistic_model.pkl")

print("Model expects:", test_model.n_features_in_, "features")

if hasattr(test_model, "feature_names_in_"):
    print("\nFeatures:")
    for i, feature in enumerate(test_model.feature_names_in_, 1):
        print(i, feature)

Model expects: 41 features

Features:
1  Age (yrs)
2 Weight (Kg)
3 Height(Cm)
4 BMI
5 Blood Group
6 Pulse rate(bpm)
7 RR (breaths/min)
8 Hb(g/dl)
9 Cycle(R/I)
10 Cycle length(days)
11 Marraige Status (Yrs)
12 Pregnant(Y/N)
13 No. of aborptions
14   I   beta-HCG(mIU/mL)
15 II    beta-HCG(mIU/mL)
16 FSH(mIU/mL)
17 LH(mIU/mL)
18 FSH/LH
19 Hip(inch)
20 Waist(inch)
21 Waist:Hip Ratio
22 TSH (mIU/L)
23 AMH(ng/mL)
24 PRL(ng/mL)
25 Vit D3 (ng/mL)
26 PRG(ng/mL)
27 RBS(mg/dl)
28 Weight gain(Y/N)
29 hair growth(Y/N)
30 Skin darkening (Y/N)
31 Hair loss(Y/N)
32 Pimples(Y/N)
33 Fast food (Y/N)
34 Reg.Exercise(Y/N)
35 BP _Systolic (mmHg)
36 BP _Diastolic (mmHg)
37 Follicle No. (L)
38 Follicle No. (R)
39 Avg. F size (L) (mm)
40 Avg. F size (R) (mm)
41 Endometrium (mm)

In [87]:
print("Number of features:", len(pcos_model.feature_names_in_))
print("\nFeature order:")
for i, feature in enumerate(pcos_model.feature_names_in_):
    print(i, "->", feature)

NameError: name 'pcos_model' is not defined

In [88]:
import joblib

pcos_model = joblib.load("pcos_logistic_model.pkl")

print("Model loaded successfully!")

Model loaded successfully!

In [89]:
print("Number of features:", pcos_model.n_features_in_)

if hasattr(pcos_model, "feature_names_in_"):
    print("\nFeature order:")
    for i, feature in enumerate(pcos_model.feature_names_in_):
        print(i, "->", feature)
else:
    print("\nThis model does not contain feature names.")

Number of features: 41

Feature order:
0 ->  Age (yrs)
1 -> Weight (Kg)
2 -> Height(Cm)
3 -> BMI
4 -> Blood Group
5 -> Pulse rate(bpm)
6 -> RR (breaths/min)
7 -> Hb(g/dl)
8 -> Cycle(R/I)
9 -> Cycle length(days)
10 -> Marraige Status (Yrs)
11 -> Pregnant(Y/N)
12 -> No. of aborptions
13 ->   I   beta-HCG(mIU/mL)
14 -> II    beta-HCG(mIU/mL)
15 -> FSH(mIU/mL)
16 -> LH(mIU/mL)
17 -> FSH/LH
18 -> Hip(inch)
19 -> Waist(inch)
20 -> Waist:Hip Ratio
21 -> TSH (mIU/L)
22 -> AMH(ng/mL)
23 -> PRL(ng/mL)
24 -> Vit D3 (ng/mL)
25 -> PRG(ng/mL)
26 -> RBS(mg/dl)
27 -> Weight gain(Y/N)
28 -> hair growth(Y/N)
29 -> Skin darkening (Y/N)
30 -> Hair loss(Y/N)
31 -> Pimples(Y/N)
32 -> Fast food (Y/N)
33 -> Reg.Exercise(Y/N)
34 -> BP _Systolic (mmHg)
35 -> BP _Diastolic (mmHg)
36 -> Follicle No. (L)
37 -> Follicle No. (R)
38 -> Avg. F size (L) (mm)
39 -> Avg. F size (R) (mm)
40 -> Endometrium (mm)

In [90]:
import joblib

pcos_model = joblib.load("models/pcos_logistic_model.pkl")

print("Model type:", type(pcos_model))

if hasattr(pcos_model, "feature_names_in_"):
    print("\nNumber of features:", len(pcos_model.feature_names_in_))
    print("\nExpected features:")
    for i, feature in enumerate(pcos_model.feature_names_in_):
        print(i, "->", feature)
else:
    print("This model does not contain feature_names_in_")

FileNotFoundError: [Errno 2] No such file or directory: 'models/pcos_logistic_model.pkl'

In [91]:
import os

print("Current folder:")
print(os.getcwd())

print("\nFiles/folders here:")
print(os.listdir())

Current folder:
C:\Users\HP\Desktop\Silent_Health_Risk_Detector\notebooks

Files/folders here:
['.ipynb_checkpoints', 'Anemia_Model.ipynb', 'Diabetes_Model.ipynb', 'EDA_Silent_Health_Risk_Detector.ipynb', 'pcos_logistic_model.pkl', 'PCOS_Model.ipynb', 'Stroke_Model.ipynb', 'stroke_model.pkl', 'Thyroid_Model.ipynb', 'thyroid_model.pkl']

In [92]:
import os

for root, dirs, files in os.walk(os.getcwd()):
    for file in files:
        if file == "pcos_logistic_model.pkl":
            print("FOUND:")
            print(os.path.join(root, file))

FOUND:
C:\Users\HP\Desktop\Silent_Health_Risk_Detector\notebooks\pcos_logistic_model.pkl

In [93]:
import os

print("Current folder:")
print(os.getcwd())

print("\nAll .pkl files found:")

for root, dirs, files in os.walk(os.getcwd()):
    for file in files:
        if file.lower().endswith(".pkl"):
            print(os.path.join(root, file))

Current folder:
C:\Users\HP\Desktop\Silent_Health_Risk_Detector\notebooks

All .pkl files found:
C:\Users\HP\Desktop\Silent_Health_Risk_Detector\notebooks\pcos_logistic_model.pkl
C:\Users\HP\Desktop\Silent_Health_Risk_Detector\notebooks\stroke_model.pkl
C:\Users\HP\Desktop\Silent_Health_Risk_Detector\notebooks\thyroid_model.pkl

In [95]:
import os

path = r"C:\Users\HP\Desktop\Silent_Health_Risk_Detector\models\pcos_logistic_model.pkl"

print("Exists:", os.path.exists(path))
print("Path:", path)

Exists: True
Path: C:\Users\HP\Desktop\Silent_Health_Risk_Detector\models\pcos_logistic_model.pkl